FROM apache/spark-py:v3.4.0

USER root
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PATH="/opt/spark/bin:${PATH}"

COPY ml ./ml
COPY streaming ./streaming
ENTRYPOINT []
